export { default as Home } from '../pages/HomePage'
export { default as Example } from '../pages/Example'
export { default as Header } from '../components/Header'
export { default as AuthCallback } from '../pages/AuthCallback'
export { default as Account } from '../pages/account'
export { default as Login } from '../pages/Login'